[package]
name = "app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
default-run = "app"
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2.3", features = ["devtools", "http-all", "macos-private-api", "notification-all", "path-all", "shell-open", "window-set-decorations", "window-start-dragging"] }
libsqlite3-sys = { version = "0.24.0", features = ["bundled-sqlcipher-vendored-openssl"] }
tokio = { version = "1.24.1", features = ["full"] }
futures-util = "0.3.25"
log = "0.4.17"
tokio-tungstenite = "0.18.0"
url = "2.3.1"
tungstenite = "0.18.0"
env_logger = "0.10.0"
windows = { version = "0.44.0", features = ["UI", "UI_ViewManagement"] }
sysinfo = "0.27.7"
window-vibrancy = "0.3.2"
objc = "0.2.7"
cocoa = "0.24.1"
cacao = { version = "0.3.2", features = ["appkit"] }
objc_id = "0.1.1"
core-graphics = "0.22.3"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

[dependencies.tauri-plugin-sql]
git = "https://github.com/tauri-apps/tauri-plugin-sql"
rev = "5379183f139625ca6c6660e2f17afa6f250066ef"
features = ["sqlite"] # or "postgres", or "mysql"
#branch = "main"
